# Generated by Django 5.0.7 on 2024-07-30 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_name', models.CharField(max_length=30, verbose_name='Full name')),
                ('sender_phone', models.CharField(max_length=14)),
                ('city_of_origin', models.CharField(max_length=20)),
                ('state_of_origin', models.CharField(choices=[('', '- Choose State -'), ('abuja', 'Abuja'), ('akwa-ibom', 'Akwa-Ibom'), ('anambra', 'Anambra'), ('bayelsa', 'Bayelsa'), ('cross-rivers', 'Cross-Rivers'), ('delta', 'Delta'), ('enugu', 'Enugu'), ('imo', 'Imo'), ('lagos', 'Lagos'), ('ogun', 'Ogun'), ('rivers', 'Rivers')], max_length=15)),
                ('reciever_phone', models.CharField(max_length=14)),
                ('reciever_address', models.CharField(max_length=90, verbose_name='Address')),
                ('reciever_name', models.CharField(max_length=30, verbose_name='Full_name')),
                ('status', models.CharField(blank=True, choices=[('', 'Status (intransit/delivered)'), ('in-transit', 'In-Transit'), ('delivered', 'Delivered'), ('packaging', 'Packaging'), ('not-shipped', 'Not Shipped')], default='packaging', max_length=15)),
                ('destination_city', models.CharField(max_length=20)),
                ('destination_state', models.CharField(choices=[('', '- Choose State -'), ('abuja', 'Abuja'), ('akwa-ibom', 'Akwa-Ibom'), ('anambra', 'Anambra'), ('bayelsa', 'Bayelsa'), ('cross-rivers', 'Cross-Rivers'), ('delta', 'Delta'), ('enugu', 'Enugu'), ('imo', 'Imo'), ('lagos', 'Lagos'), ('ogun', 'Ogun'), ('rivers', 'Rivers')], max_length=15)),
                ('transport_method', models.CharField(choices=[('', 'Select (Air/Land)'), ('air', 'Air'), ('land', 'Land'), ('water', 'Water')], max_length=15)),
                ('substance_type', models.CharField(choices=[('', 'Liquid/Solid'), ('liquid', 'Liquid'), ('solid', 'Solid'), ('both', 'Both')], max_length=15)),
                ('unit_of_measurement', models.CharField(choices=[('', 'Kg/Lbs'), ('l', 'L'), ('kg', 'Kg'), ('lbs', 'lbs')], max_length=15)),
                ('units', models.DecimalField(decimal_places=1, max_digits=20)),
                ('request_refund', models.BooleanField(default=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('updated_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_timestamp'],
            },
        ),
    ]
